"""added foreign key column to task

Revision ID: 807eea87a6b5
Revises: 0e59237c7b0c
Create Date: 2024-11-08 18:31:27.273407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '807eea87a6b5'
down_revision = '0e59237c7b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('goal_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'goal', ['goal_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('goal_id')

    # ### end Alembic commands ###
